# Generated by Django 6.0.8 on 2026-09-14 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_set_password_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'المستخدمة', 'verbose_name_plural': 'المستخدمات'},
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='عالجتها'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='حساب مشرفة؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('participant', 'مشاركة'), ('group_supervisor', 'مشرفة فصل'), ('general_supervisor', 'مشرفة عامة'), ('superadmin', 'مشرفة النظام')], max_length=30, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='اسم المستخدمة'),
        ),
    ]
