# Generated by Django 6.0.8 on 2026-09-14 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0015_tasksubmission_text_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'فصل', 'verbose_name_plural': 'الفصول'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['user__full_name'], 'verbose_name': 'مشاركة', 'verbose_name_plural': 'المشاركات'},
        ),
        migrations.AlterField(
            model_name='circleattendance',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_attendances', to='participants.participant', verbose_name='المشاركة'),
        ),
        migrations.AlterField(
            model_name='circleattendance',
            name='recorded_by',
            field=models.ForeignKey(limit_choices_to={'role': 'group_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سجّلته'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='اسم الفصل'),
        ),
        migrations.AlterField(
            model_name='group',
            name='supervisor',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'group_supervisor'}, to=settings.AUTH_USER_MODEL, verbose_name='المشرفات'),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to='participants.participant', verbose_name='المشاركة'),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='recorded_by',
            field=models.ForeignKey(limit_choices_to={'role': 'group_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سجّلته'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='academic_stage',
            field=models.CharField(choices=[('grade_7', 'أول متوسط'), ('grade_8', 'ثاني متوسط'), ('grade_9', 'ثالث متوسط')], max_length=10, verbose_name='المرحلة الدراسية'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='participants.group', verbose_name='الفصل'),
        ),
        migrations.AlterField(
            model_name='pointsledgerentry',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_ledger_entries', to='participants.participant', verbose_name='المشاركة'),
        ),
        migrations.AlterField(
            model_name='pointsresetsnapshot',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_snapshots', to='participants.participant', verbose_name='المشاركة'),
        ),
        migrations.AlterField(
            model_name='pointsresetsnapshot',
            name='reset_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='نفّذته'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='participants.participant', verbose_name='المشاركة'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to='participants.participant', verbose_name='المشاركة'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='يظهر للمشاركة عند رفض تسليمها', verbose_name='سبب الرفض'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='راجعتها'),
        ),
        migrations.AlterField(
            model_name='weeklyactivityattendance',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_activity_attendances', to='participants.participant', verbose_name='المشاركة'),
        ),
        migrations.AlterField(
            model_name='weeklyactivityattendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سجّلته'),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='allowed_formats',
            field=models.CharField(help_text='يمكن اختيار أكثر من صيغة، يكفي المشاركة تقديم واحدة منها', max_length=50, verbose_name='الصيغ المسموحة'),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأتها'),
        ),
    ]
