# Generated by Django 6.0.8 on 2026-09-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0016_alter_group_options_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='academic_stage',
            field=models.CharField(choices=[('grade_7', 'أول متوسط'), ('grade_8', 'ثاني متوسط'), ('grade_9', 'ثالث متوسط'), ('grade_10', 'أول ثانوي'), ('grade_11', 'ثاني ثانوي'), ('grade_12', 'ثالث ثانوي')], max_length=10, verbose_name='المرحلة الدراسية'),
        ),
    ]
