"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# Was hardcoded to [] (fine for local dev — Django auto-allows
# localhost/127.0.0.1 when DEBUG=True and this is empty). Made
# env-configurable so production behind Nginx/Docker can set real host(s)
# via ALLOWED_HOSTS in .env.docker without editing this file. default=[]
# keeps local `.env` behavior identical since it doesn't set this var.
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# TLS is terminated by Nginx in the Docker deployment; it proxies to Gunicorn
# over plain HTTP and forwards the original scheme in `X-Forwarded-Proto`.
# Without this, request.is_secure() stays False behind the proxy and Django's
# CSRF origin check rejects every POST made over HTTPS (login form, every
# other form). Trusting this header is safe here because Gunicorn is only
# reachable through Nginx on the internal Docker network, never directly.
# No effect in local dev (nothing sets the header over plain http://).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "participants",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.ForcePasswordSetupMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Local dev (.env, no USE_POSTGRES) keeps the original SQLite default
# untouched. Production via Docker sets USE_POSTGRES=True in .env.docker
# to switch to PostgreSQL, reading connection details from the same file.
if env.bool("USE_POSTGRES", default=False):
    DATABASES = {
        "default": {
            "ENGINE": env("DB_ENGINE", default="django.db.backends.postgresql"),
            "NAME": env("DB_NAME"),
            "USER": env("DB_USER"),
            "PASSWORD": env("DB_PASSWORD"),
            "HOST": env("DB_HOST"),
            "PORT": env("DB_PORT", default="5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Authentication Model

AUTH_USER_MODEL = "accounts.User"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    "accounts.backends.NationalIDOrUsernameBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ar-sa"

TIME_ZONE = "Asia/Riyadh"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_DIRS = [BASE_DIR / "static"]

STATIC_URL = "static/"

# Required by `collectstatic` (docker/entrypoint.sh runs it on every
# container start) — was unset entirely before, which raises
# ImproperlyConfigured the instant collectstatic runs. Harmless locally:
# nothing in local dev calls collectstatic, so this path is simply never
# touched outside Docker. Matches docker-compose.yml's static_volume
# mount and nginx.conf's `alias /app/staticfiles/`.
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# django-unfold admin theme
# RTL itself needs no setting here: Unfold's base template sets
# `dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}"` from Django's own
# {% get_current_language_bidi %}, and LANGUAGE_CODE="ar-sa" above is
# already bidi — verified: dir="rtl" is already present on every admin
# page. The primary color and site branding are set via Unfold's own
# official settings below; static/css/admin-custom.css (loaded through
# the official STYLES hook) only fixes the handful of spots Unfold ships
# no official setting for (see that file's comments and the task report).
UNFOLD = {
    "SITE_TITLE": "لوحة تحكم جُمان",
    "SITE_HEADER": "لوحة تحكم جُمان",
    "STYLES": [
        "/static/css/admin-custom.css",
    ],
    "COLORS": {
        # Juman's brand teal (#40A595) replacing Unfold's default purple.
        # Shade "600" is the exact brand hex — it's the shade Unfold's own
        # templates/widgets use for buttons, active nav links, focus
        # rings, and checked states (bg-primary-600 / border-primary-600).
        # The rest of the ramp (50-950) is #40A595 tinted toward white /
        # shaded toward black at the same hue, so light/dark-mode surfaces
        # stay a coherent teal instead of just recoloring one shade.
        "primary": {
            "50": "oklch(98.1% 0.0053 197.070)",
            "100": "oklch(95.8% 0.0130 185.094)",
            "200": "oklch(91.0% 0.0292 183.304)",
            "300": "oklch(85.3% 0.0450 184.007)",
            "400": "oklch(76.5% 0.0717 183.233)",
            "500": "oklch(70.6% 0.0853 182.689)",
            "600": "oklch(65.9% 0.0964 180.967)",  # #40A595
            "700": "oklch(58.1% 0.0844 180.539)",
            "800": "oklch(49.9% 0.0707 180.962)",
            "900": "oklch(41.5% 0.0583 180.410)",
            "950": "oklch(33.8% 0.0455 181.973)",
        },
    },
}
